# Copyright 2023 Aleksandr Ovsiankin
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#	  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if .Values.metrics.podMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: '{{ template "service.name" . }}'
  namespace: '{{ .Release.Namespace }}'
spec:
  selector:
    matchLabels:
      "app": '{{ template "service.name" . }}'
  podMetricsEndpoints:
    - port: {{ .Values.metrics.podMonitor.port }}
      path: {{ .Values.metrics.podMonitor.path }}
      interval: {{ .Values.metrics.podMonitor.interval }}
{{- end }}
